# Generated by Django 6.0.4 on 2026-05-14 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_category_subscribers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcategory',
            old_name='categorys',
            new_name='category',
        ),
    ]
