# Generated by Django 6.0.4 on 2026-05-14 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_categorys_postcategory_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcategory',
            old_name='posts',
            new_name='post',
        ),
    ]
