"""
Django settings for NewsPortall project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-kd*^a=up00di=6k)p)hqoznekv4!kbd!qq(77gt^tuh!a+t_7l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'news.apps.NewsConfig',
    'django.contrib.sites',
    'django.contrib.flatpages',
    'django_filters',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.yandex', # Провайдер яндекс

    # Добавляем планировщик задач:
    'django_apscheduler',

]

# Настройки для социальных сетей
SOCIALACCOUNT_PROVIDERS = {
    'yandex': {
        'SCOPE': [
            'login:email',
            'login:info',
        ],
        'AUTH_PARAMS': {'access_type': 'online'},
    }
}

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',

    # СЮДА ДОБАВЛЯЕМ СТРОЧКУ ПЕРЕВОДА:
    'django.middleware.locale.LocaleMiddleware',

    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware',

    "allauth.account.middleware.AccountMiddleware",
]




ROOT_URLCONF = 'NewsPortall.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Указываем Django искать шаблоны в корневой папке templates
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,  # Это включает поиск шаблонов внутри allauth
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',  # Обязательно для allauth
            ],
        },
    },
]

WSGI_APPLICATION = 'NewsPortall.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',

        # ИСПРАВЛЕНО: Добавляем таймаут внутрь существующего блока DATABASES
        'OPTIONS': {
            'timeout': 20,
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

LANGUAGES = [
    ('ru', 'Русский'),
    ('en', 'English'),
]

# Указываем Django, где искать нашу папку locale
LOCALE_PATHS = [
    BASE_DIR / 'locale'  # В новых версиях Django пишется так, это проще и без import os
]



ACCOUNT_AUTHENTICATION_METHOD = 'email' # устаревшие названия настроек
ACCOUNT_EMAIL_REQUIRED = True # устаревшие названия настроек
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = False # Имя пользователя теперь необязательно устаревшие названия настроек
ACCOUNT_EMAIL_VERIFICATION = 'mandatory' # Чтобы не настраивать почтовый сервер сразу (для тестов) добавил mandatory вместо none

# добавил вместо закомиченых вверху
#ACCOUNT_LOGIN_METHODS = {'email'} # новые настройки для новой версии библиотеки django-allauth
#ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*'] # новые настройки для новой версии библиотеки django-allauth


STATIC_URL = 'static/'

LOGIN_URL = '/accounts/login/' # Куда слать анонима
LOGIN_REDIRECT_URL = '/news/' # Адрес, на который пользователь попадет сразу после входа

# Куда переходить после выхода из системы
LOGOUT_REDIRECT_URL = '/news/'



AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend', # Стандартный вход по username
    'allauth.account.auth_backends.AuthenticationBackend', # Вход через allauth (по почте)
]

ACCOUNT_FORMS = {'signup': 'news.forms.BasicSignupForm'}

# Письма будут печататься прямо в консоль (терминал) PyCharm для тестового тестирования, без привязки к реальной почты
#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# settings.py (В самом конце файла)

# 1. Переключаем Django из режима консоли в режим реальной отправки в интернет
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'


# для проверки почты прямо в jango
#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# 2. Подключаем сетевой шлюз Яндекса
EMAIL_HOST = 'smtp.yandex.ru'
EMAIL_PORT = 465
EMAIL_USE_SSL = True

# 3. Данные ящика-робота, который настроили в Шаге 1
EMAIL_HOST_USER = 'edv123evdokimov@yandex.ru'    # Почта моего робота
EMAIL_HOST_PASSWORD = 'itrsngndwpcmivti' # Пароль приложения моего робота
DEFAULT_FROM_EMAIL = 'edv123evdokimov@yandex.ru' # Имя отправителя в письме



# settings.py (В самый конец файла)

# Адрес подключения Django к запущенному Redis
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0'


# Настройки для Celery
# settings.py (В самый конец файла)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE  # Синхронизируем часовой пояс с Django


# Для еженедельной рассылки новостей по расписанию
# settings.py (В самый конец файла)
from celery.schedules import crontab  # Обязательный импорт планировщика

# Настраиваем расписание периодических задач Celery Beat
CELERY_BEAT_SCHEDULE = {
    # Придумываем любое уникальное название для нашей задачи
    'weekly_digest_every_monday_8am': {
        # Указываем точный путь к нашей готовой задаче из файла tasks.py
        'task': 'news.tasks.weekly_send_email_task',

        # Настраиваем время запуска строго по ТЗ:
        # day_of_week=1 означает Понедельник (в Celery: 1=Пн, 7=Вс)
        # hour=8, minute=0 означает ровно 8:00 утра
        'schedule': crontab(hour=8, minute=0, day_of_week=1),
        #'schedule': crontab(minute='*/1'), # Запуск каждую минуту для теста!

    },
}


# Настройка кэша Django через сервер Redis
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',  # Используем базу номер 1, чтобы не мешать Celery
    }
}

# ==============================================================================
# НАСТРОЙКА ЛОГИРОВАНИЯ (ИТОГОВОЕ ЗАДАНИЕ 4.1)
# ==============================================================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    # 1. ФИЛЬТРЫ (Условия, когда логи работают)
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',  # Работает только при DEBUG = True
        },
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',  # Работает только при DEBUG = False
        },
    },

    # 2. ФОРМАТТЕРЫ (Как выглядят строчки в файлах и консоли)
    'formatters': {
        'console_debug': {
            'format': '{asctime} [{levelname}] {message}',
            'style': '{',
        },
        'console_warning': {
            'format': '{asctime} [{levelname}] {message} (Path: {pathname})',
            'style': '{',
        },
        'file_general': {
            'format': '{asctime} [{levelname}] In module "{module}": {message}',
            'style': '{',
        },
        'file_errors': {
            'format': '{asctime} [{levelname}] {message} (Path: {pathname})\nStack trace:\n{exc_info}',
            'style': '{',
        },
        'file_security': {
            'format': '{asctime} [{levelname}] In module "{module}": {message}',
            'style': '{',
        },
        'mail_errors': {
            'format': '{asctime} [{levelname}] {message} (Path: {pathname})',
            'style': '{',
        },
    },

    # 3. ХЕНДЛЕРЫ (Куда отправлять записи: в консоль, файлы или на почту)
    'handlers': {
        # Вывод в консоль для DEBUG сообщений
        'console': {
            'level': 'DEBUG',
            'filters': ['require_debug_true'],  # Только при DEBUG = True
            'class': 'logging.StreamHandler',
            'formatter': 'console_debug',
        },
        # Отдельный хендлер для WARNING и выше в консоль (чтобы добавить pathname и exc_info)
        'console_high': {
            'level': 'WARNING',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'console_warning',
        },
        # Файл общего назначения general.log
        'file_general': {
            'level': 'INFO',
            'filters': ['require_debug_false'],  # Только при DEBUG = False
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'general.log',
            'formatter': 'file_general',
        },
        # Файл ошибок errors.log
        'file_errors': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'errors.log',
            'formatter': 'file_errors',
        },
        # Файл безопасности security.log
        'file_security': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'security.log',
            'formatter': 'file_security',
        },
        # Отправка на почту администраторам
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],  # Только при DEBUG = False
            'class': 'django.utils.log.AdminEmailHandler',
            'formatter': 'mail_errors',
        },
    },

    # 4. ЛОГГЕРЫ (Регистраторы, которые собирают события из разных частей Django)
    'loggers': {
        # Главный логгер django
        'django': {
            'handlers': ['console', 'console_high', 'file_general'],
            'level': 'DEBUG',
            'propagate': True,
        },
        # Ошибки запросов пользователей
        'django.request': {
            'handlers': ['file_errors', 'mail_admins'],
            'level': 'ERROR',
            'propagate': False,  # Выключаем дублирование в родительский логгер django
        },
        # Ошибки внутреннего сервера
        'django.server': {
            'handlers': ['file_errors', 'mail_admins'],
            'level': 'ERROR',
            'propagate': False,
        },
        # Ошибки в HTML-шаблонах
        'django.template': {
            'handlers': ['file_errors'],
            'level': 'ERROR',
            'propagate': False,
        },
        # Ошибки при работе с базой данных
        'django.db.backends': {
            'handlers': ['file_errors'],
            'level': 'ERROR',
            'propagate': False,
        },
        # Логгер безопасности
        'django.security': {
            'handlers': ['file_security'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


ADMINS = [
    ('Дмитрий', 'edv123evdokimov@yandex.ru'), # Сюда Django будет слать письма об ошибках
]
